### ISSUE TITLE
GeoServer (Test): MobiData-BW:radvis_cycle_network error

### ISSUE THREAD

**Issue by rforster32** [mobidata-bw/ipl-orchestration#127]
When entering the `MobiData-BW:radvis_cycle_network` layer, the following error occurs:

`Beim Laden der Attribute für diesen Layer ist ein Fehler aufgetreten: ERROR: relation "streckenabschnitt" does not exist Position: 30`

When opening the tab "Publizierung" I get this error: 

```
org.apache.wicket.WicketRuntimeException: Exception in rendering component: [DropDownChoice [Component id = kml.regionateAttribute]]
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2630)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1658)
	at org.apache.wicket.Component.internalRender(Component.java:2403)
	at org.apache.wicket.Component.render(Component.java:2331)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1516)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1719)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1694)
	at org.apache.wicket.MarkupContainer.renderAssociatedMarkup(MarkupContainer.java:800)
	at org.apache.wicket.markup.html.panel.AssociatedMarkupSourcingStrategy.renderAssociatedMarkup(AssociatedMarkupSourcingStrategy.java:77)
	at org.apache.wicket.markup.html.panel.PanelMarkupSourcingStrategy.onComponentTagBody(PanelMarkupSourcingStrategy.java:112)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2606)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1658)
	at org.apache.wicket.Component.internalRender(Component.java:2403)
	at org.apache.wicket.Component.render(Component.java:2331)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1516)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1719)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1694)
	at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1649)
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2606)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1658)
	at org.apache.wicket.Component.internalRender(Component.java:2403)
	at org.apache.wicket.Component.render(Component.java:2331)
	at org.apache.wicket.markup.html.list.ListView.renderItem(ListView.java:584)
	at org.apache.wicket.markup.html.list.ListView.renderChild(ListView.java:573)
	at org.apache.wicket.markup.repeater.AbstractRepeater.onRender(AbstractRepeater.java:102)
	at org.apache.wicket.Component.internalRender(Component.java:2403)
	at org.apache.wicket.Component.render(Component.java:2331)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1516)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1719)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1694)
	at org.apache.wicket.MarkupContainer.renderAssociatedMarkup(MarkupContainer.java:800)
	at org.apache.wicket.markup.html.panel.AssociatedMarkupSourcingStrategy.renderAssociatedMarkup(AssociatedMarkupSourcingStrategy.java:77)
	at org.apache.wicket.markup.html.panel.PanelMarkupSourcingStrategy.onComponentTagBody(PanelMarkupSourcingStrategy.java:112)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2606)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1658)
	at org.apache.wicket.Component.internalRender(Component.java:2403)
	at org.apache.wicket.Component.render(Component.java:2331)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1516)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1719)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1694)
	at org.apache.wicket.MarkupContainer.renderAssociatedMarkup(MarkupContainer.java:800)
	at org.apache.wicket.markup.html.panel.AssociatedMarkupSourcingStrategy.renderAssociatedMarkup(AssociatedMarkupSourcingStrategy.java:77)
	at org.apache.wicket.markup.html.panel.PanelMarkupSourcingStrategy.onComponentTagBody(PanelMarkupSourcingStrategy.java:112)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2606)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1658)
	at org.apache.wicket.Component.internalRender(Component.java:2403)
	at org.apache.wicket.Component.render(Component.java:2331)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1516)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1719)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1694)
	at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1649)
	at org.apache.wicket.markup.html.form.Form.onComponentTagBody(Form.java:1710)
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2606)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1658)
	at org.apache.wicket.Component.internalRender(Component.java:2403)
	at org.apache.wicket.Component.render(Component.java:2331)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1516)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1719)
	at org.apache.wicket.Page.onRender(Page.java:879)
	at org.apache.wicket.markup.html.WebPage.onRender(WebPage.java:141)
	at org.apache.wicket.Component.internalRender(Component.java:2403)
	at org.apache.wicket.Component.render(Component.java:2331)
	at org.apache.wicket.Page.renderPage(Page.java:1018)
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:97)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
	at org.apache.wicket.protocol.http.WicketServlet.doPost(WicketServlet.java:159)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:166)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:73)
	at org.geoserver.ows.HTTPHeadersCollector.doFilter(HTTPHeadersCollector.java:48)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
	at org.geoserver.filters.HTTPMethodFilter.doFilter(HTTPMethodFilter.java:36)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:194)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:43)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:39)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:53)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.geoserver.security.filter.GeoServerUserNamePasswordAuthenticationFilter.doFilter(GeoServerUserNamePasswordAuthenticationFilter.java:122)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:106)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:97)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilterInternal(GeoServerSecurityContextPersistenceFilter.java:72)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.geoserver.filters.XFrameOptionsFilter.doFilter(XFrameOptionsFilter.java:100)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:49)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Could not load feature type attribute list
	at org.geoserver.wms.web.publish.KMLLayerConfigPanel$AttributeNamesModel.load(KMLLayerConfigPanel.java:77)
	at org.geoserver.wms.web.publish.KMLLayerConfigPanel$AttributeNamesModel.load(KMLLayerConfigPanel.java:57)
	at org.apache.wicket.model.LoadableDetachableModel.getObject(LoadableDetachableModel.java:137)
	at org.apache.wicket.markup.html.form.AbstractChoice.getChoices(AbstractChoice.java:230)
	at org.apache.wicket.markup.html.form.AbstractChoice.onComponentTagBody(AbstractChoice.java:376)
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2606)
	... 183 more
Caused by: java.io.IOException: Error occurred building feature type
	at org.geotools.jdbc.JDBCFeatureSource.buildFeatureType(JDBCFeatureSource.java:379)
	at org.geotools.jdbc.JDBCDataStore.createFeatureSource(JDBCDataStore.java:907)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:338)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:308)
	at org.geotools.data.store.ContentDataStore.getSchema(ContentDataStore.java:294)
	at org.geotools.jdbc.JDBCDataStore.createVirtualTable(JDBCDataStore.java:329)
	at org.geoserver.catalog.VirtualTableCallback.initialize(VirtualTableCallback.java:56)
	at org.geoserver.catalog.ResourcePool.acquireFeatureType(ResourcePool.java:1085)
	at org.geoserver.catalog.ResourcePool.getCacheableFeatureType(ResourcePool.java:1070)
	at org.geoserver.catalog.ResourcePool.tryGetFeatureType(ResourcePool.java:1053)
	at org.geoserver.catalog.ResourcePool.getFeatureType(ResourcePool.java:1045)
	at org.geoserver.catalog.ResourcePool.getFeatureType(ResourcePool.java:1030)
	at org.geoserver.catalog.impl.FeatureTypeInfoImpl.getFeatureType(FeatureTypeInfoImpl.java:134)
	at jdk.internal.reflect.GeneratedMethodAccessor239.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.geoserver.catalog.impl.ModificationProxy.invoke(ModificationProxy.java:144)
	at com.sun.proxy.$Proxy121.getFeatureType(Unknown Source)
	at org.geoserver.wms.web.publish.KMLLayerConfigPanel$AttributeNamesModel.load(KMLLayerConfigPanel.java:71)
	... 189 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "streckenabschnitt" does not exist
  Position: 30
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:246)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.geotools.jdbc.JDBCFeatureSource.getColumnMetadata(JDBCFeatureSource.java:871)
	at org.geotools.jdbc.JDBCFeatureSource.buildFeatureType(JDBCFeatureSource.java:197)
	... 207 more
Beim Laden der Seite ist ein Fehler aufgetreten
```

**Comment by rforster32** [comment]
@richardforsterNVBW

**Comment by hbruch** [comment]
The asset has never been materialized:
<img width="1376" alt="image" src="https://github.com/mobidata-bw/ipl-orchestration/assets/2187389/7e958da6-5999-40e9-8fa9-022d88f939d5">

Auto-Materialize has to be enabled explicitly:

<img width="1311" alt="image" src="https://github.com/mobidata-bw/ipl-orchestration/assets/2187389/5dd2f423-2454-492c-8f1c-fbd76748ff0f">

**Comment by rforster32** [comment]
I wanted to change the layer configuration in order to add a style in addition to the default style. With the error, I cannot access.
